### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by eye0fra**
- Updated "Environment preparation" section
 - Shortened route names due 63 limit characters

### CODE REVIEW

**Comment by geoand** [comment]
Thanks for the PR!

LGTM, @metacosm ?

**Comment by metacosm** [comment]
Changing the route name might impact tests downstream…

**Comment by eye0fra** [comment]
Interesting, in this case we can add a note for the upstream that you can encounter the limit of 63 characters or we can as well remove the Routes after downstream validation: 

- on pom.xml <fabric8.openshift.generateRoute>false</fabric8.openshift.generateRoute>
- under .openshiftio/application.yaml remove the Route section

Because all the requests come from the istio-ingress-gateway and I don't think we need it for this scenario, unless I missed something :)

**Comment by geoand** [comment]
Can we update the PR to only include the doc change?

**Comment by eye0fra** [comment]
@geoand @metacosm  what are your thoughts ?

**Comment by eye0fra** [comment]
@geoand done

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
